### ISSUE TITLE
cytoscape should be a peer dependency

### ISSUE THREAD

**Issue by cappslock** [plotly/react-cytoscapejs#17]
Rather than bundling cytoscape, it would be nice to express it as a peer dependency pegged to the major version. I'm happy to provide a PR for this.

**Comment by maxkfranz** [comment]
A peer dependency would not be appropriate within the semantics of package.json.  This is a proper dependency, not a plugin dependency.

**Comment by akx** [comment]
Seconding this.

The same way `react` and `react-dom` are peer dependencies here, `cytoscape` should be. 

I bumped into a problem where `.use()`ing a Cytoscape plugin didn't work because there were multiple versions of Cytoscape bundled in, and `use`ing the plugin only registered it in the Cytoscape _not_ being used by `react-cytoscapejs`.
