### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by leecalcote** [plotly/react-cytoscapejs#57]
Hi @maxkfranz, @alexcjohnson, @chriddyp, @jackparmer,

In context of #55, a group of open source contributors in the [Layer5 community](https://github.com/layer5io) are considering using `react-cytoscape`. As we consider this, I would like to connect with you to understand how we can best collaborate and support the project; whether the project is still active and so on. Could you speak to the state of this effort?

Thanks!
\- @leecalcote, @anirudhjain75, @kushthedude, @vineethvanga18, @josegonzalez @josegonzalez @dhruv0000

**Comment by alexcjohnson** [comment]
Hi @leecalcote - This project is in active use by [dash-cytoscape](https://github.com/plotly/dash-cytoscape) (ping @xhlulu, the primary dash-cytoscape maintainer). We're also starting to use it in the dash renderer devtools https://github.com/plotly/dash/pull/1179. We haven't been making a lot of changes to react-cytoscapejs itself recently because it has served those needs in its current state, but we're certainly happy to help it grow and evolve, and we'd love to help you guys contribute.

As you can see from the other PRs and issues here, we're not watching activity in this repo very closely, because it has generally been stable for our own purposes. But you're welcome to ping me and I'll make sure the right people join the conversation.

**Comment by TimNZ** [comment]
@alexcjohnson 
https://github.com/plotly/react-cytoscapejs/issues/21

Please make cytoscape a peerDependencies

**Comment by leecalcote** [comment]
@alexcjohnson, thanks so much for this response. We couldn’t have hoped for a better one. We’re organizing the team and effort now and hope to be a good collaborator as the need arises (if it arises). Much appreciated. @TimNZ’s inquiry is unrelated to my question here. 

Hi @TimNZ, being unacquainted, I don’t want to intermix my discussion with whatever the focus of your needs/questions might be. I’m closing this issue given and encourage you to engage separately, if needed.

**Comment by TimNZ** [comment]
I saw an opp to tag on to the query of project status in context of action/progress on issues, and I took it  😅
